### ISSUE TITLE
Add usual number of workflows to this repo

### ISSUE THREAD

**Issue by umbynos** [arduino/dfu-discovery#23]
Add the usual number of workflows:

- [x] check-go-dependencies-task.yml
- [x] check-go-task.yml
- [x] check-license.yml
- [x] check-markdown-task.yml
- [x] check-taskfiles.yml
- [x] check-workflows-task.yml
- [x] publish-go-tester-task.yml (should use the `task dist:*` and not the usual `task go:build`)
- [x] sync-labels.yml

**Comment by MatteoPologruto** [comment]
Done:
- #25 
- #27 
- #28 
- #30 
- #31 
- #35 
- #36 
- #37
